shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - packages/**
  - fixtures/*
overrides:
  '@eslint/core': ^1.2.1
  synckit: ^0.11.12
  undici-types: ^8.1.0
onlyBuiltDependencies:
  - esbuild
